# Generated by Django 4.2.2 on 2023-06-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age_at_missing', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=10)),
            ],
        ),
    ]
